### ISSUE TITLE
Feature Request: Support -output-directory

### ISSUE THREAD

**Issue by MatthiasNieuwenhuisen** [xqms/graphicscache#1]
I use the pdflatex parameter -output-directory to keep the source directory clean. It would be great if the graphicscache and graphicscacheout.* files also would be written to the specified output directory.

A workaround could be to subsume the build artifacts of this extension into one directory, e.g., into the graphicscache directory.

**Comment by xqms** [comment]
related: https://tex.stackexchange.com/questions/294931/access-value-of-output-directory

**Comment by xqms** [comment]
I implemented your suggested workaround and set the output dir to `graphicscache/` for the pdflatex runs. Using the original `-output-directory` is not easily possible.
