### ISSUE TITLE
mgs shouldn't be assumed on windows

### ISSUE THREAD

**Issue by u-fischer** [xqms/graphicscache#17]
mgs is a miktex specific variant of ghostscript. It doesn't exist if texlive is used.

**Comment by xqms** [comment]
Hey, thanks for the feedback! I have had no Windows users so far, so I'm very glad you tested this ;)

Do you know if a usual texlive windows distribution includes ghostscript? Is it just called `gs`?

We probably need to detect that during import of the package. I'll try to come up with a way to do that.

**Comment by u-fischer** [comment]
There is a ghostscript in texlive, the binary itself is not in the path but you can call it with the wrapper `rungs`. 

And a side remark: \immediate\write18 doesn't work in a native luatex. It does work in your package because you load the shellesc package which overloads \write. But it would be cleaner to use `\ShellEscape`  instead of `\immediate\write18`.

**Comment by xqms** [comment]
Should be fixed in #20.
