### ISSUE TITLE
Use of variables in includegraphics breaks hashing

### ISSUE THREAD

**Issue by MatthiasNieuwenhuisen** [xqms/graphicscache#2]
When using variables as parameters in \includegraphics, the hash of different figures might be the same.

The following example should include two figures with different size ([Expected result](https://github.com/xqms/graphicscache/files/2446960/expected-result.pdf)):
```latex
\documentclass{article}

\usepackage{graphicx}
\usepackage{graphicscache}

\newlength{\figurewidth}

\begin{document}
\begin{figure}
\centering
\setlength{\figurewidth}{0.5\linewidth}
\includegraphics[width=\figurewidth]{left-fig}
\caption{50\% figure}
\end{figure}

\begin{figure}
\centering
\setlength{\figurewidth}{0.1\linewidth}
\includegraphics[width=\figurewidth]{left-fig}
\caption{10\% figure}
\end{figure}

\end{document}
```
but the actual result are two figures of equal size ([Actual result](https://github.com/xqms/graphicscache/files/2446959/actual-result.pdf)).

LaTeX and image files: [parameter-hashing-issue.zip](https://github.com/xqms/graphicscache/files/2446991/parameter-hashing-issue.zip)

**Comment by xqms** [comment]
Fixed!

**Comment by xqms** [comment]
Note: doing this correctly (actually expanding and parsing the arguments) allowed me to render the images using standalone tex documents in 55ebcf7b612 - much faster than the preview package :-)

**Comment by MatthiasNieuwenhuisen** [comment]
Wow, it's super fast now!
